#!/bin/sh -e
#
# iplinux-bootstrap
# © 2008-2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

VERSION=0.1.1

GPG_KEY=http://ftp.iplinux.org/gpgkey

PATH=$PATH:libshell
. shell-error
. shell-getopt

#
# Probably need to be configurable in future
#

host_components="host/tools host/cross"
host_packages="dpkg-cross dpkg cross-shell"

# ---

# Our little config.guess
guess_hostarch() {
    if [ $(uname -s) != "Linux" ]; then
        echo unknown
        return
    fi
    case "$(uname -m)" in
        i?86|pentium*) echo i386;;
        x86_64)        echo amd64;;
        *)             echo unknown;;
    esac
}

hostarch() {
    dpkg --print-architecture 2>/dev/null || guess_hostarch
}

#
# Bootstraps chroot and performs configuration enough to run $work_dir/enter
#
generate_chroot_name="Generating chroot"
generate_chroot() {
    $root_cmd sh -c "$chroot_env DEBOOTSTRAP_DIR=$(pwd)/debootstrap debootstrap/debootstrap --include=sudo,less --arch=$chroot_arch $debian_suite $work_dir $debian_mirror"
    if [ "$?" != 0 ]; then
        echo "Failed to bootstrap $debian_suite from $debian_mirror to $work_dir"
        exit 1
    fi

    # -- hostname (for sudo) --

    HOSTNAME=$(hostname)
    $root_sh "echo 127.0.0.1 localhost $HOSTNAME >> $work_dir/etc/hosts"

    # -- 'build' user --

    [ -n "$UID" ] || UID=`id -u`

    $root_cmd $chroot_cmd $work_dir /usr/sbin/adduser --home /build --uid $UID --disabled-password --disabled-login --gecos 'IPlinux build user' build

    # -- sudo --

    TMPFILE=$(mktemp)
    echo "Defaults env_keep+=http_proxy, env_keep+=ftp_proxy" > $TMPFILE
    echo "build ALL=(ALL) NOPASSWD:ALL" >> $TMPFILE
    $root_cmd mv $TMPFILE $work_dir/etc/sudoers
    $root_cmd chown root:root $work_dir/etc/sudoers
    $root_cmd chmod 440 $work_dir/etc/sudoers

    # -- $work_dir/enter --

    TMPFILE=$(mktemp)
    sed -e "s,@@HTTP_PROXY@@,$http_proxy,g" \
        -e "s,@@FTP_PROXY@@,$ftp_proxy,g" < enter.in > $TMPFILE
    $root_cmd mv $TMPFILE $work_dir/enter
    $root_cmd chmod +x $work_dir/enter

}

populate_chroot_name="Populating chroot"
populate_chroot() {
    # -- sources.list --

    TMPFILE=$(mktemp)
    echo "deb $debian_mirror $debian_suite main" > $TMPFILE
    echo "deb $mirror $suite $host_components" >> $TMPFILE
    $root_cmd mv $TMPFILE $work_dir/etc/apt/sources.list

    # -- no APT recommends by default

    echo "APT { Install-Recommends 'false\'; };" > $TMPFILE
    $root_cmd mv $TMPFILE $work_dir/etc/apt/apt.conf.d/02no-recommends

    # -- GPG key --

    cp gpgkey $work_dir/tmp
    $work_dir/enter sudo apt-key add /tmp/gpgkey
    rm -f $work_dir/tmp/gpgkey

    # -- packages --

    $work_dir/enter sudo apt-get update
    $work_dir/enter sudo apt-get dist-upgrade --yes --force-yes
    $work_dir/enter sudo apt-get install --yes --force-yes $host_packages
}

configure_chroot_name="Configuring chroot"
configure_chroot() {
    TMPFILE=$(mktemp)
    echo "SUITE=$suite
REPO=$mirror
ROOT_CMD=sudo"  > $TMPFILE
    $root_cmd mv $TMPFILE $work_dir/etc/cross-shell/config
}

bootstrap_host_name="Bootstraping host"
bootstrap_host() {
    $work_dir/enter cross-bootstrap-host
}

bootstrap_target_name="Bootstrapping targets"
bootstrap_target() {
    for arch in $(echo $target_archs | sed 's/,/ /g'); do
        echo " --> $arch"
        $work_dir/enter cross-bootstrap-target $arch
    done
}

usage() {
    echo "Usage: ${0##*/} [OPTION]... <target-dir>"
    echo "Bootstrap IPlinux devenv chroot"
    echo
    cat <<EOF
      -h|--help             display this help and exit
      -V|--version          display version information and exit
      -v|--verbose          don't turn off the output of tools

      --http-proxy=P        http proxy to use to obtain packages
      --ftp-proxy=P         ftp proxy to use to obtain packages

      --debian-mirror=U     debian mirror to use. this should be
                            an URL understandable by debootstrap
                            (defaults to '$debian_mirror')
      --debian-suite=S      debian suite to use. change only if you
                            know what are you doing!
                            (defaults to '$debian_suite')
      --mirror=U            iplinux mirror to use
                            (defaults to '$mirror')
      --suite=S             iplinux suite to use
                            (defaults to '$suite')
      --target-archs=A,B... target architectures (defaults to '$target_archs')

      --root-cmd=C          command to gain root (defaults to '$root_cmd')

EOF
}

export LC_ALL=C
	
TMP=$(getopt --long help,version,verbose,http-proxy:,ftp-proxy:,debian-mirror:,mirror:,suite:,root:,target-archs:,no-bootstrap-rootfs,root-cmd: -o hvV -- "$@")

if [ $? != 0 ]; then
    exit 1
fi

eval set -- "$TMP"

debian_mirror=http://ftp.de.debian.org/debian/
debian_suite=lenny
mirror=http://ftp.iplinux.org/iplinux/
suite=asimov
root_cmd=sudo
chroot_env=
target_archs=

while true; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -V|--version)
            echo "iplinux-bootstrap $VERSION"
            exit 0
            ;;
        -v|--verbose)
            verbose=true
            export verbose
            shift
            ;;
        --http-proxy)
            http_proxy="$2"
            chroot_env="$chroot_env http_proxy=$2"
            shift 2
            ;;
        --ftp-proxy)
            ftp_proxy="$2"
            chroot_env="$chroot_env ftp_proxy=$2"
            shift 2
            ;;
        --debian-mirror)
            debian_mirror="$2"
            shift 2
            ;;
        --debian-suite)
            debian_suite="$2"
            shift 2
            ;;
        --mirror)
            mirror="$2"
            shift 2
            ;;
        --suite)
            suite="$2"
            shift 2
            ;;
        --target-archs)
            target_archs="$2"
            shift 2
            ;;
        --no-bootstrap-rootfs)
            no_bootstrap_rootfs=1
            shift
            ;;
        --root-cmd)
            root_cmd="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unexpected argument in arguments list: $1"
            exit 1
            ;;
    esac
done

if [ $# != 1 ]; then
    usage
    exit 0
fi

case "$1" in
    /*) work_dir="$1";;
    *)  work_dir=$(pwd)/$1;;
esac

root_sh="$root_cmd sh -c"

case "$(hostarch)" in
    i386|amd64)
        chroot_cmd="chroot"
        chroot_arch=$(hostarch)
        ;;
    *)
        echo "Unable to detect the host architecture."
        echo "Please file a bug report with output of"
        echo "* dpkg --print-architecture (if you use a Debian-based system)"
        echo "* uname -s; uname -m (in all other cases)"
        exit 1
esac

check_ok() {
    RET=$?
    if [ $RET -ne 0 ]; then
        echo "Chroot generation failed"
    fi
    exit $RET
}
trap check_ok 0 HUP PIPE INT QUIT TERM

echo
echo "** If script stops without \"You can enter newly created...\", then it broke."
echo

tasks="generate_chroot populate_chroot configure_chroot bootstrap_host bootstrap_target"
tasknum=0
tasksnum=$(echo $tasks | wc -w)

for task in $tasks; do
    tasknum=$(($tasknum+1))
    echo "=>> "$(eval "echo $"$task"_name")" [$tasknum/$tasksnum]"
    $task
done

echo
echo
echo "You can enter newly created IPlinux build environment by issuing"
echo "the following command:"
echo "    $work_dir/enter"
echo
echo
