#!/bin/sh -x

if [ "$#" -ne 1 ]; then
   echo "Usage: make-release <version>"
fi

VERSION="$1"
DIR="iplinux-bootstrap-$1"
DIST="$DIR.tar.bz2"

WWW_PATH="/srv/www/ftp.iplinux.org/htdocs/contrib/iplinux-bootstrap"

if ! git status | grep -q 'nothing to commit (working directory clean)'; then
    git status
    exit 1
fi

git tag -s "$VERSION" -m "$VERSION"
git push origin
git push origin --tags

git archive --prefix="$DIR"/ HEAD \
    | bzip2 > "$DIST"

rsync "$DIST" "openinkpot.org:$WWW_PATH"
ssh openinkpot.org ln -sf "$DIST" "$WWW_PATH/iplinux-bootstrap-LATEST.tar.bz2"
