#!/bin/sh -e

D=$(date +%Y%m%d)
DIR=oi-devenv-$(date +%Y%m%d)

./oi-bootstrap --no-bootstrap-rootfs "$@" $DIR
sudo chroot $DIR apt-get clean
sudo chroot $DIR rm -f /var/cache/apt/archives-*/*.deb
sudo cp setup $DIR
sudo tar cjf $DIR.tar.bz2 $DIR
sudo rm -rf $DIR
